/* This file was generated by SableCC (http://www.sablecc.org/). 

   The file was later modified to specialize it for 
   the constant integer expression AST.

   AnalysisAdapter is a default implementation of the IAnalysis interface.
   It calls the defaultCase on all nodes.
   There is a hook for each node in this interface (e.g. casePlusExpr, etc).
      
*/

package ast.visitor;

import java.util.Hashtable;

import ast.node.*;

public class AnalysisVisitor implements IAnalysis
{

    public void casePlusExp(PlusExp node)
    {
        defaultCase(node);
    }

    public void caseMinusExp(MinusExp node)
    {
        defaultCase(node);
    }

    public void caseMulExp(MulExp node)
    {
        defaultCase(node);
    }

    public void caseIntegerExp(IntegerExp node)
    {
        defaultCase(node);
    }

    public void caseToken(Token node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
