/* This file was generated by SableCC (http://www.sablecc.org/). 

   IAnalysis is an interface for a visitor/switch on nodes in the AST.
   There is a hook for each node in this interface (e.g. casePlusExpr, etc).
      
*/


package ast.visitor;

import ast.node.*;

public interface IAnalysis extends ISwitch
{
    void casePlusExp(PlusExp node);
    void caseMinusExp(MinusExp node);
    void caseMulExp(MulExp node);
    void caseIntegerExp(IntegerExp node);
    void caseToken(Token node);

}
