/* This file was generated by SableCC (http://www.sablecc.org/). 
 * Then modified.
 */

package ast.node;

import ast.visitor.IAnalysis;

@SuppressWarnings("nls")
public final class IntegerExp extends IExp
{
    private Token _literal_;

    public IntegerExp()
    {
        // Constructor
    }

    public IntegerExp(
        @SuppressWarnings("hiding") Token _literal_)
    {
        // Constructor
        setLiteral(_literal_);

    }

    @Override
    public Object clone()
    {
        return new IntegerExp(
            cloneNode(this._literal_));
    }

    public void accept(ISwitch sw)
    {
        ((IAnalysis) sw).caseIntegerExp(this);
    }

    public Token getLiteral()
    {
        return this._literal_;
    }

    public void setLiteral(Token node)
    {
        if(this._literal_ != null)
        {
            this._literal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._literal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._literal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._literal_ == child)
        {
            this._literal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._literal_ == oldChild)
        {
            setLiteral((Token) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
