/* This file was generated by SableCC (http://www.sablecc.org/). 
 * Then modified.
 */

package ast.node;

/**
 * ISwitch is the highest level interface for switches (or visitors).
 * The ast.visitor package contains visitor traversal classes that
 * derive from ISwitch.
 * 
 * @author mstrout
 *
 */
public interface ISwitch
{
        // Empty body
}
