/* This file was generated by SableCC (http://www.sablecc.org/). 
 * Then modified.
 */

package ast.node;

/**
 * The ISwitchable interface enables objects to be visited by an ISwitch,
 * as in the visitor design pattern.
 * @author mstrout
 *
 */
public interface ISwitchable
{
    void accept(ISwitch sw);
}
