
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 08 03:56:58 EST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int PLUS = 4;
  public static final int NUMBER = 3;
  public static final int SEMI = 7;
  public static final int MINUS = 5;
  public static final int TIMES = 6;
  public static final int EOF = 0;
}

